### main 게시글 리스트 확인
GET {{url}}/feeds?page=2&categoryId=1
Content-Type: application/json

### main 임시 게시글 리스트 가져오기
GET {{url}}/feeds/temp
Content-Type: application/json
Authorization: Bearer {{token}}

### main 임시 게시글 저장
POST {{url}}/feeds/temp
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content": "temp test content asdfasdfasdfasfd",
  "file_links": "https://project-review.s3.ap-northeast-2.amazonaws.com/11/167704815631603bca3977c0680e5cf8b47e691f531eb.png"

}

### main 임시 게시글 수정
PATCH {{url}}/feeds/temp
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "feedId": 107,
  "content": "임시저장 수정 테스트",
  "file_links": "https://project-review.s3.ap-northeast-2.amazonaws.com/11/167704815631603bca3977c0680e5cf8b47e691f531eb.png"

}

### main 정식 게시글 등록
POST {{url}}/feeds/post
Content-Type: application/json
Authorization: {{token}}

{
  "title": "test title",
  "content": "test content asdfasdfasdfasfd",
  "estimation": 1,
  "category": 1,
  "status": 1,
  "file_links": "https://project-review.s3.ap-northeast-2.amazonaws.com/11/bb7eb601836583430fcdfac70dd0eb3b193eec18a5b9fe9a7804f1c8c85ee6c4.png "
}
