### upload image file to s3
POST {{url}}/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
authorization: Bearer {{token}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="testimage2.png"
Content-type: image/png

< ./testimage2.png
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="testPDF.pdf"
Content-type: pdf/png

< ./testPDF.pdf


### delete image file from s3
DELETE {{url}}/upload
Content-Type: application/json

{
  "file_links": [
    "https://project-review.s3.ap-northeast-2.amazonaws.com/11/16771335271165927d4c2c1af785db6627cf4edd4ca88.pdf"
  ]
}