table users as u {
  id int [pk, increment, not null]
  nickname varchar(20) [not null, unique]
  password varchar(100) [not null]
  email varchar(20) [not null, unique]
  created_at datetime [not null, default: `now()`]
  updated_at "datetime default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" [not null,note:'update time']
}

table feeds as f {
  id int [pk, increment, not null]
  userId int [not null, ref: > u.id]
  title varchar(250) [not null]
  content varchar(10000) [not null]
  estimationId tinyint [ref: > e.id]
  categoryId int [not null, ref: > ct.id]
  statusId tinyint [not null, ref: > fst.id]
  posted_at datetime
  created_at datetime [not null, default: `now()`]
  updated_at "datetime default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" [not null,note:'update time']
}

table feed_status as fst  {
  id tinyint [pk, increment, not null]
  status varchar(100) [not null] // published, temporary, deleted
  created_at datetime [not null, default: `now()`]
  updated_at "datetime default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" [not null,note:'update time']
}

table estimation as e {
  id tinyint [pk, increment, not null]
  estimation varchar(50) [not null]
  // double like, like
  created_at datetime [not null, default: `now()`]
  updated_at "datetime default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" [not null,note:'update time']
}

table  symbol as s {
  id tinyint [pk, increment, not null]
  symbol varchar(50) [not null] // like, I have this too.
  created_at datetime [not null, default: `now()`]
  updated_at "datetime default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" [not null,note:'update time']
}

table feed_symbol as fs {
  id int [pk, increment, not null]
  userId int [not null, ref: > u.id]
  feedId int [not null, ref: > f.id]
  symbolId tinyint [not null, ref: > s.id]
  created_at datetime [not null, default: `now()`]
  updated_at "datetime default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" [not null,note:'update time']
   Indexes {
    (userId, feedId) [unique]
  }
}

table upload_files as uf  {
  id int [pk, increment, not null]
  is_img boolean [not null]
  file_link varchar(500) [not null]
  created_at datetime [not null, default: `now()`]
  updated_at "datetime default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" [not null,note:'update time']
}

table feed_uploadFiles as fu {
  id int [pk, increment, not null]
  feedId int [not null, ref: > f.id]
  upload_filesId int [not null, ref: > uf.id]
  created_at datetime [not null, default: `now()`]
  updated_at "datetime default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" [not null,note:'update time']
}

table categories as ct  {
  id int [pk, increment, not null]
  category varchar(100) [not null]
  // book, electronic, ect
  created_at datetime [not null, default: `now()`]
  updated_at "datetime default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" [not null,note:'update time']
}

table comments as c  {
  id int [pk, increment, not null]
  userId int [not null, ref: > u.id]
  feedId int [not null, ref: > f.id]
  comment varchar(1000) [not null]
  reply_id int [default: `0`]
  is_private boolean [default: `false`]
  is_deleted boolean [default: `false`]
  created_at datetime [not null, default: `now()`]
  updated_at "datetime default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" [not null,note:'update time']
}

