openapi: 3.0.0
servers:
  - description: project_review localhost API document
    url: http://localhost:8000
info:
  version: "1.0.0"
  title: project_review-API
  description: The API for project_review
paths:
  /users/signup:
    $ref: "./user.yaml"