name: Integration Coverage Badge

# This workflow has been modified based on the following action.
# https://github.com/marketplace/actions/coverage-badge
on:
  workflow_run:
    workflows: ["Integration Tests"]
    branches: ["main"]
    types:
      - completed

jobs:
  badge:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Generate Coverage Badge
        run: |
          npm install -g badgen-cli
          COVERAGE=$(node -p 't=require(`./coverage/coverage-summary.json`).total,Math.min(...`lines|statements|functions|branches`.split(`|`).map(k=>t[k].pct))')
          COLOR=$(node -p '+$COVERAGE >= 90 ? `green` : +$COVERAGE >= 60 ? `orange` : `red`')
          mkdir -p badges
          badgen -j Integration Coverage -s $COVERAGE% -c $COLOR > badges/coverage.svg
      - name: Deploy Badges
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update badges [skip ci]"
          branch: gh-pages
          skip_fetch: true
          skip_checkout: true
      - name: Checkout Back
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
